### ISSUE TITLE
Doesnt seem to work in Web API Project or Being called from another application

### ISSUE THREAD

**Issue by herrozerro** [tjscience/RoboSharp#19]
I have created a small application that copies a set of template folders from one network share to another.  And It works in Visual studio and if I click on the program manually.  But I want to have this be able to be called from another application.

Example 1: I put my application out on a network share to be accessible by multiple users, opening the application manually works, but calling it through a VBA shell command I get the following exception:

11/2/2016 7:55:48 AM: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RoboSharp.RoboCommand.<>c__DisplayClass48_0.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CopyFoldersPermissions.MJEFolderCopy.Main(String[] args) in C:\TFS\Development\UtilityDevelopment\CopyFoldersPermissions\FolderCopy.cs:line 68
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RoboSharp.RoboCommand.<>c__DisplayClass48_0.<Start>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

line 68 is just: 

copy.Start("domain", ConfigurationManager.AppSettings.Get("username"),
                    ConfigurationManager.AppSettings["password"]).Wait();

The root folder is copied but no subfolders are created.  Another example is when I shift + right-click the folder and open a command window there so I get Z:Copyfolder.exe, the same exception.  I suspect it might have something to do with how the shell call is happening, but I have never run into this before.

Example 2: I took all of my existing code and placed it in a WEB API application, The application pool is a user who has access to the network shares, and I run the code.  No exceptions this time, but I get the same behavior of just copying the root folder without the subfolders.

In both cases, I am using the correct flags, and like I said earlier, it seems to work as a standalone executable as long as it's manually opened by the user, but I want to automate it.

**Comment by herrozerro** [comment]
Changing my code to use this as a task and awaiting it in the WebAPI has fixed my issue.
