### ISSUE TITLE
Calling Dispose in OnCommandCompleted() on RoboCommand instance results in Task Exception

### ISSUE THREAD

**Issue by bruceburge** [tjscience/RoboSharp#32]
[Edit] After running the code, the issue is, if you call dispose in the completed method, it will fire before the stop method is called at the end of the start task, leaving the process, not null, but no process associated with it. [/Edit]

![image](https://user-images.githubusercontent.com/6773890/31151049-7e7b39da-a85b-11e7-8c3a-9902b75bdb99.png)

**Comment by ScotiaBaker** [comment]
I've hit this as well - this reliability issue is a blocker for me.

For reference, the exception is:

            Error: Unhandled exception (0x80131500): System.AggregateException: TaskExceptionHolder_UnhandledException ---> System.InvalidOperationException: No process is associated with this object.
               at System.Diagnostics.Process.EnsureState(State state)
               at System.Diagnostics.Process.get_HasExited()
               at RoboSharp.RoboCommand.Stop()
               at RoboSharp.RoboCommand.<Start>b__48_1(Task continuation)
               at System.Threading.Tasks.Task.Execute()
               --- End of inner exception stack trace ---
               at System.Threading.Tasks.TaskExceptionHolder.Finalize()
            ---> (Inner Exception #0) System.InvalidOperationException: No process is associated with this object.
               at System.Diagnostics.Process.EnsureState(State state)
               at System.Diagnostics.Process.get_HasExited()
               at RoboSharp.RoboCommand.Stop()
               at RoboSharp.RoboCommand.<Start>b__48_1(Task continuation)
               at System.Threading.Tasks.Task.Execute()<---
            */

**Comment by bruceburge** [comment]
I've created something that should resolve the issue, but the reality is, that when the OnCommandCompleted() is fired, stop is called, which in turn calls dispose.  So simply removing the dispose call from OnCommandCompleted() removes the issue, and the disposes the object all the same.
