### ISSUE TITLE
Copy from/to remote server doesn't work [WITH SOLUTION]

### ISSUE THREAD

**Issue by Dekuguy** [tjscience/RoboSharp#43]
in **"RoboCommand.cs" Line 188** you try to create the destination directory. But you are not authenticated on the other server.

I created a solution from Jon Cole(https://stackoverflow.com/questions/8901476/creating-windows-folders-using-impersonation?answertab=active#tab-top).

I attached the new RoboCommand file:
[RoboCommand.txt](https://github.com/tjscience/RoboSharp/files/1720124/RoboCommand.txt)

**Comment by Dekuguy** [comment]
**UPDATE:**
In Line 178 where you check if the source Directory exists of course also if you copy **from** a remote server.

New attached RoboCommand file:
[New RoboCommand.txt](https://github.com/tjscience/RoboSharp/files/1720138/RoboCommand.txt)

**Comment by bruceburge** [comment]
You may want to consider creating a pull request, as those are much easier to deal with.

**Comment by tjscience** [comment]
As @bruceburge said, please create a pull request. Thanks.

**Comment by RFBomb** [comment]
#108 is superceded by #110, which has the changes this proposed by #45, which were supposed to resolve this.

**Comment by PCAssistSoftware** [comment]
fixed by #110

**Comment by alexaka1** [comment]
Why is [this](https://github.com/tjscience/RoboSharp/blob/5d6594a32751d4657d76c1eb6ac6caf06eb8ea56/RoboSharp/RoboCommand.cs#L396) .Net Framework only? 

Wrapping `new RoboCommand().Start()` inside an `WindowsIdentity.RunImpersonatedAsync()` results in `No process is associated with this object.` exception.
```c#
 at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at RoboSharp.RoboCommand.<>c__DisplayClass105_0.<GetRoboCopyTask>b__1(Task continuation)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RoboSharp.RoboCommand.StartAsync(String domain, String username, String password)
```

Edit:
Further debugging yielded this, on line `521` of `RoboCommand.cs` it throws:
```c#
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'Robocopy.exe' with working directory 'path\to\my\project\bin\Debug\net6.0-windows'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RoboSharp.RoboCommand.<>c__DisplayClass105_0.<<GetRoboCopyTask>b__0>d.MoveNext()
```

**Comment by PCAssistSoftware** [comment]
@alexaka1 - this should now be resolved with latest commit which adds support for .NET Core as well
